### ISSUE TITLE
2021 arkistointi /2021 -polkuun

### ISSUE THREAD

**Issue by Hamatti** [koodiklinikka/palkkakysely#4]
Jotta saadaan pidettyä uuden palkkakyselyn tullessa tulosten urli kivana, ois kiva jos tän viimevuotisen sais /2021-polun taa ja sitten uuden joko suoraan tai /2022-polulle.

Tein issuen, koska en oo ihan varma miten toteutetaan. Voiko kamat siirtää 2021-kansioon, tehä index-filun roottiin ja all good?

Laitoin @akx sut assigneeksi, mutta voin myös itse kontribuoida jos vinkkaat miten kannattaa toteuttaa.

**Comment by akx** [comment]
@Hamatti Way ahead of you ;-) Valmistelin tätä tuossa https://github.com/koodiklinikka/palkkakysely/pull/2 ...
