### ISSUE TITLE
Seurantaissue: Kehitysideoita vuodelle 2023

### ISSUE THREAD

**Issue by Hamatti** [koodiklinikka/palkkakysely#8]
Jos tulee mieleen hyviä ideoita seuraavan vuoden palkkakyselyn kehittämiseksi, kommentoi tähän issueen (ja jos joku huutelee Slackissa ideoita, linkkaa niille tää issue)

**Comment by Sirri** [comment]
Mahdollisena kehityskohteena parantaa uskallusta vastata sensitiivisempiin kohtiin kuten yritykseen, jossa työskentelee. Luvataan esimerkiksi, ettei yritystä julkaista, ellei datapisteitä tule esim > 5. Vaatii datan sanitointia ennen julkaisua, mutta tuottaisi kivasti lisäinformaatiota.

**Comment by Hamatti** [comment]
Keskusteltiin että ensi vuoden kyselyyn mietitään datan käytölle joku sopiva lisenssi, esim [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.fi) joka mahdollistaa datan käytön, mutta vaatii mainitsemaan Koodiklinikan.

Ajatuksena ei ole rajoittaa käyttöä vaan ennemminkin helpottaa sitä, kun lisenssit ovat selkeät.
