### ISSUE TITLE
Palkkakysely 2023 - kyselyn rakentaminen

### ISSUE THREAD

**Issue by Hamatti** [koodiklinikka/palkkakysely#9]
Moikka moi vaan! On taas tullut aika kartoittaa Koodiklinikan väen palkkoja ja tuloja.

Ennen kuin laukaistaan varsinainen kysely tulille, on ollut perinteiden mukaista että on mahdollisuus vaikuttaa kyselyn sisältöön, koska _design by community_ on parempi kuin _design by Juhis_.

Alla on viime vuoden kysymyksiä ja vastausvaihtoehtoja. Kommentoi tähän issueen ideoita, parannusehdotuksia, uusia tai poistettavia kysymyksiä tai niiden muotoiluja. Kaikkia ideoita ei luvata toteuttaa, koska pyrin balansoimaan lyhyttä kyselyä johon jengi jaksaa vastata.

Joka vuosi nousee ideana että ois kiva tietää mitä tech stackia on käytössä yms, mutta sanon jo nyt että pidän ne poissa tästä kyselystä ja toivottavasti joku tekee State of Koodiklinikka -kyselyn esim tammikuussa jossa kartoitetaan näitä.

Viime vuonna 2022 kysely oli jaettu kahtia, toinen kysymyspatteristo **palkansaajille** ja toinen **laskuttajille**. Vastauksia kertyi 684, joista palkansaajia 616 ja laskuttajia 68.

## Yhteiset kysymykset

- Ikä (5v haarukoilla)
- Sukupuoli (vapaakenttä)
- Työkokemus (vuosina)
- Vapaa sana

## Laskuttajat

- Montako vuotta olet tehnyt laskuttavaa työtä alalla?
- Mitä palveluja tarjoat? (vapaa kenttä)
- Tuntilaskutus (ALV 0%, euroina)
- Hankitko asiakkaasi itse suoraan vai käytätkö välitysfirmojen palveluita? (itse, välitysfirmojen kautta, molemmat)
- Mistä asiakkaat ovat? (Suomesta, ulkomailta)

## Palkansaajat

- Työpaikka (jos tahtoo kertoa)
- Missä kaupungissa työpaikkasi pääasiallinen toimisto sijaitsee? (PK-seutu, Tampere, Oulu, Turku, Jyväskylä, Lahti, Kuopio, muu)
- Millaisessa yrityksessä työskentelet (konsultti, tuotetalo, ei-it-firma jossa softa tukeva toiminto, julkinen tai kolmas sektori)
- Työaika (100%, 80%, 60%, 50%, muu)
- Rooli (vapaa kenttä)
- Etänä vai lähityössä? (Pääosin tai kokonaan etätyö, Pääosin tai kokonaan toimistolla, Jotain siltä väliltä)
- Kuukausipalkka (brutto, euroina)
- Vuositulot (sis. bonukset, osingot yms, euroina)
- Vapaa kuvaus kokonaiskompensaatiomallista
- Onko palkkasi nykyroolissasi mielestäsi kilpailukykyinen? (kyllä / ei)

**Comment by Hamatti** [comment]
Slackista:

**Arttu Taipale**
> Onko koskaan kysytty koulutustaustaa? Vois olla kiinnostavaa nähdä saako erityisesti tietotekniikkaa/ohjelmistokehitystä opiskelleet kovempaa liksaa kuin vaikkapa DI-taustalla alalle tulleet, alanvaihtajat, tai muut.

**Comment by joneteus** [comment]
Parhaan vertailtavuuden vuoksi voisi olla hyvä tarkentaa että kuukausipalkka/vuositulot tulisi ilmoittaa 100% työaikaa vastaavana palkkana silloin kun tekee pienemmällä prosentilla.

**Comment by akx** [comment]
@joneteus Tuo on ratkaistu tyypillisesti jälkikäteen noilla datanmälväysskripteillä, mutta toki jos sen itse vastaaja jaksaa ja pystyy laskemaan, sitä parempi :D

**Comment by MatiasPuhakka** [comment]
Kiinnostais tietää paljonko vastaajan palkka on noussut vuoden takaisesta (% tai €)

**Comment by rask** [comment]
Ite kaipaisin, että rooleihin liittyen olisi joku "individual contributor, people manager, product/project manager" tyylinen ns. ylätason valintaboksi tuon vapaan kentän lisäksi. Hieman ehkä helpottaisi datan kanssa puljaamista kun tekee vertailuja jne.

**Comment by Hamatti** [comment]
Slackista: 

Harri Määttä
> mites tuo "Etänä vai lähityössä?" kysymys. mietin, että olisiko helpompaa tilastoida, jos olisi jotain tyyliin "Montako prosenttia työajasta keskimäärin teet etänä?" tai "Kuinka ison osan työajasta vietät toimistolla" tai jotain vastaavaa, johon vastaus olisi jotain väliltä 0-100. tietty binaariset vastaukset ovat vielä helpompia louhia, mutta myös yksinkertaistaa rajusti

**Comment by Hamatti** [comment]
Slackista Jaakko:

> Voisiko olla kysymys: "Kuinka monta prosenttia palkkasi/palkkiosi on muuttunut viimeisen 12 kuukauden aikana?"
> Eli siis kysymys, joka luotaa mahdollisen edellisen palkankorotuskierroksen tuloksia. Tai friikkujen hintojen elämistä.

**Comment by Hamatti** [comment]
Teemu teki pohjatyötä ja kävi läpi viime vuoden roolivastauksia ja teki niille alustavaa kategorisointia:

# Intro
​
This doc contains the categorization of unique job titles from the kk-22 salary quiz, created to help choosing some set of predefined titles to simplify analyses by disallowing the variety of written forms for same titles.
​
There is a very strong bias towards technical roles/titles, so it might be worth looking into some list of common roles and leaving it to the participants to select one and include a separate free-form "title" field.
​
## Some notes
​
- Lead developer vs. development lead 
- There is a very storng bias towards technical roles/titles => might be worth to look for a common list of roles in IT and use that for "pre-defined roles" to avoid ignoring potential participants who feel that they are not included?
- To avoid multiroles, instruct the participants to select the most matching / primary role.
- In addition to the "role", add title as a freeform field.
- Maybe a separate field for the level {jr, sr, lead, staff} => avoids parsing when answering questions like "what can I make w/o changing the role"
- Potential source for fairer categorization: https://www.bls.gov/ooh/Computer-and-Information-Technology/Software-developers.htm#tab-8 ?
​
​
# C-level
- Teknologiajohtaja
- Jonkinmoinen johtaja
- CTO
- Cto
- CIO
- Director
​
# Manager
- Lähiesimies, ohjelmistokehittäjä (Drupal backend)
- IT-Manager
- Engineering Manager
- Tekninen Projektipäällikkö
- Manager
​
## Leading manager(?)
- Principal Engineer / Team Lead
- Team Lead
- Tiiminvetäjä
- Lead developer
- Lead Engineer
- Lead Developer (Full-stack)
- Team leader
- Engineering team lead
- Lead dev
- Lead backend dev
- Lead Developer
- Projektipäällikkö
- Palvelupäällikkö 
- Team lead
- Technical lead
- Engineering Lead
- DevOps Manager
- Tech Lead
- Team lead/full-stack
- Full-stack/liidi
- Team Lead / Ohjelmistokehittäjä
- Engineering lead
​
- Palvelupäällikkö
- Kehittäjä, tuotepäällikkö
​
# Software Developer
- Ohjelmistokehittäjä
- Devaaja
- Ohjelmoija
- Vanhempi ohjelmistokehittäjä
- Developer
- Senioridevaaja
- Ohjelmistokehitys
- Senior Developer
- Sovelluskehittäjä
- Senior ohjelmistokehittäjä
- Software Developer
- Senior developer
- Senior/Lead developer
- Senior software developer
- Software developer
- Junior sw developer
- Junior Developer
- Ohjelmistosuunnittelija
- Vanhempi ohjelmistosuunnittelija
- Ohjelmistokehittäjä 
- Ohjelmistosuunnittelija & scrum-master
- C++/Qt/QML Ohjelmistokehittäjä
- .NET developer
- WordPress Developer
- MDM-kehittäjä
​
## Frontend developer
- Frontend koodari
- Frontend-kehittäjä, scrum master
- Senior Frontend Developer
- Senior kehittäjä, front 
- Ohjelmistokehittäjä (frontend ja legacy-hommia)
- Ohjelmistokehittäjä (enimmäkseen Frontend)
- Frontend/full-stack
- Frontend devaaja
- Junior frontend developer
- Frontend developer
- Senior frontend-kehittäjä
- Ohjelmistokehittäjä (frontend)
- Frontend-kehittäjä
- Frontend ohjelmistokehittäjä
- Senior front end kehittäjä
- Junior frontend dev
- Ohjelmistokehittäjä (frontend-heavy full-stack, web/mobile))
- Frontend
- Front-end
​
## Backend developer
- Backend developer
- Ohjelmistokehittäjä (backend)
- Backend-devaaja
- Backend ohjelmistokehittäjä
- Backend
- Junior backend
- Ohjelmistokehittäjä, backend pääosin, mutta kaikkea mahtuu
- Ohjelmistokehittäjä, enimmäkseen backend
- Backend kehittäjä
- Ohjelmoija, backend
- Senior Backend Developer
- Backend-ohjelmistokehittäjä
- Senior backend engineer
- Back-end
- Ohjelmistokehittäjä, backend
- Backend Ohjelmistokehittäjä
​
## Fullstack developer
- Full-stack-ohjelmistokehittäjä
- Ohjelmistokehittäjä full-stack, laitteistokehitys, tekoäly/koneoppiminen
- Full-stack fronttipainotuksella
- Fullstack devaaja
- Full-stack devaaja
- Senior full-stack developer
- Full-stack ohjelmistokehittäjä 
- Fullstack Developer
- Full-stack -ohjelmistokehittäjä
- Full Stack Developer
- Softakehittäjä, full stack
- Full-stack -kehittäjä
- Senior developer, full-stack
- Full stack -kehittäjä
- Sovelluskehittäjä, full-stack
- Full-Stack dev
- Fullstack/azure kehittäjä
- Ohjelmistokehittäjä, full stack
- Ohjelmistokehittäjä full stack
- Java Full Stack
- Full stack
- Full stack (ainut työntekijä)
- Frontend-painotteinen FullStack software dev
- Full-stack pilvikehittäjä
- Full-stack developer (Cloud)
- Full-stack sovelluskehittäjä
- Senior full-stack software developer
- Full-stack web developer
- Senion full-stack kehittäjä, analyytikko
- Full stack everything
- Devaaja (full stack + mobiili)
- Full-stack -devaaja
- Fullstack + testaus
- Full stack ohjelmistokehittäjä
- Senior full-stack developer/arkkitehti
- Full-stack/frontend
- FullStack Azure Developer
- Full-stack/projektipäällikkö 
- Full-stack dev
- Full stack web developer
- Full-stack programmer
- Ohjelmistokehittäjä, full-stack, arkkitehti, devops-asiantuntija
- Ohjelmistokehittäjä, mallia full-stack
- Full-stack konsultti
- Full-stack-kehittäjä, team lead
- Full-stack ohjelmistokehittäjä/arkkitehti
- Full-stack lead developer
​
## Mobile developer
- Mobiili / backend devaaja
- Senior Mobile Engineer
- Ohjelmistokehittäjä, mobiili
- Mobiilikehittäjä
- Ohjelmistokehittäjä (mobile, web) 
- Android kehittäjä
​
​
## Web developer (necessary at all?)
- Web developer
- Web Developer
​
​
## Embedded developer
- Embedded C++
- Ohjelmistokehittäjä, sulautetut
​
​
# Integration developer
- Integraatiokehittäjä
​
​
# Solutions developer (similar to integration dev?)
- Solution developer
- Solution manager
- Asiakasvastaava
- Developer Support Engineer
​
​
# Software Engineer
- Software-engineer
- Senior Software Developer
- Senior software engineer
- Software Engineer
- Senior Software Engineer
- Backend Engineer
- Software engineer
- Senior SW Engineer, embedded systems
- Staff Software Engineer
- Principal software engineer
- Software engineer, Full-stack
- Full stack engineer 
- Senior Software Engineer, API development
​
​
# Architect
- Full-stack / Arkkitehti
- Arkkitehti
- Järjestelmäarkkitehti
- Ohjelmistoarkkitehti
- Solution Architect
- Arkkitehtu
- Sovellusarkkitehti
- Full-stack/arkkitehti
- Ohjelmistokehittäjä ja arkkitehti
- Pilviarkkitehti
- Ohjelmistökehittäjä/arkkitehti
- Arkkitehti / Full-stack kehittäjä
- Arkkitehti, data, backend
- Arkkitehti, fullstack dev backend-painotuksella, devops
​
​
# (Dev)Ops / SRE
## SRE
- DevOps / SRE
- SRE
- Site Reliability Engineer
- Senior Site Reliability Engineer
​
## DevOps
- DevOps-konsultti
- DevOps konsultti
- DevOps
- DevOps Engineer
- Järjestelmäasiantuntija: DevOps
- DevOps Specialist
- DevOps jamppa
- Senior Devops Engineer
- DevOps/SRE Engineer
- Devops Engineer
- DevSecOps Engineer
​
## Cloud engineer
- Pilvi-infra
- Cloud infra
- Lead cloud engineer
- Cloud + DevOps
- Pilviarkkitehti/kehittäjä
- Pilviasiantuntija
- Cloud specialist
- Cloud Developer
- Cloud
​
## Ops engineer
- Systems Specialist, suomeksi ops eli alustapystytystä, ylläpitoa, pilveä, konesalia
- System specialist
- Ops
- Operations
​
## Network engineer
- Verkkoinsinööri
​
## Database administrator / DBA
- Database Administrator, Linux-palvelujen ylläpitäjä, inframies
​
​
# Teaching & Research
## Research
​
- Tutkimuspäällikkö
- Tutkija, projektipäällikkö
- Data Scientist
- Data scientist
- Senior data scientist
- Datatieteilijä
​
## Teaching
​
- Opettaja
- Varhaiskasvatuksen avustaja
​
​
# Data
## Data engineer
​
- Backend/Data Engineer
- Senior Data Engineer
- Data Engineer
- Data Developer
- Data engineer
​
## Data architect
- Data-arkkitehti
​
​
# Testing/QA
- Ohjelmistotestaaja
- Testaaja
- QA
- Q&A tester
- Lead test engineer
- Testiautomaatiokehittäjä
​
​
# UX, usability etc.
- Asiantuntija käyttöliittymä suunnittelussa sekä frontti kehityksessä
- UX-suunnittelija
​
​
# Designer
- Ohjelmistokehittäjä ja designer
​
​
# Service manager
- Service Manager DevOps
- Service Manager Trainee
​
# Product owner
- Product owner
- Product Owner
​
​
# Business developer(?)
- Business development
​
​
​
# Misc & multirole
- Staff Engineer
- Yrittäjä
- Sekatyömies (projari, arkkitehti, full-stack, firman strategi)
- Ohjelmistokehittäjä, tiiminvetäjä, esihenkilö
- Konsultti
- SAP-konsultti
- Senior Consultant
- Core Server, Query Optimization 
- Suunnittelija
- Web-analyytikko
- Asiantuntija
- Projekti-insinööri
- Ict-admin
​
# Multirole
- Multirole
- Kehittäjä, arkkitehti ja tiiminvetäjä
- Laidasta laitaan koodia (frontend, backend, cloud, devops, arkkitehturointi, yms.) + esimieshommat
- Ohjelmistokehittäjä, arkkitehti ja projektipäällikkö
- Backend, devops, projektipäällikkö
- Programmer/DevOps
- Devaaja/arkkitehti

**Comment by Hamatti** [comment]
Omia ajatuksiani tähän roolikysymykseen:

1. Esimerkiksi webbipuolella on paljon overlapia: merkatako itsensä "software developer"-, "web developer"- tai "full-stack developer"-rooliin? Lisäksi ainakin omasta kokemuksestani devaajilla on usein sitä että on montaakin hattua. 
2. Pitäisikö ehkä olla mahdollisuus valita useita rooleja? Mietin itse siitä näkökulmasta että jos fronttidevaajana tahdon nähdä miten muut webbidevaajat tienaavat, ei olisi niin isoa riskiä sille että joku on merkannut full-stack, joku web ja joku software developer ja tällöin hajaantunut vastaukset.
3. Mun ehdotus olisi että kaikki kategoriat, joiden alle menisi vähän kaikkea, jätetään pois ja vapaakentäksi. Näin saataisiin noi yleisimmät napattua samoihin kategorioihin, mutta kaikki muut näkisi yksittäisinä vastauksina. Tässä erityisesti edellä olevasta listasta esim noi multirole-ja misc-kategorioiden roolit.
